# The build part for Netlify with a Nuxt project
[build]
publish='dist'
command='nuxt generate'
environment = { NODE_VERSION = "20.15.1" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''
